RubyOnRails_seedProject/config/routes.rb
Rails.application.routes.draw do
  resources :pos
  resources :products
  resources :sales
  resources :shops
  get 'home/index'

  resources :profiles
  resources :name_profiles
  #resources :miscellaneous


  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #root :to => 'miscellaneous#blank_page'
  root :to => 'home#index'
  # Miscellaneous
  get 'miscellaneous/login',
      to: 'miscellaneous#login',
      as: :miscellaneous_login
  get 'miscellaneous/register',
      to: 'miscellaneous#register',
      as: :miscellaneous_register
  get 'miscellaneous/forgot_password',
      to: 'miscellaneous#forgot_password',
      as: :miscellaneous_forgot_password
  get 'miscellaneous/locked_screen',
      to: 'miscellaneous#locked_screen',
      as: :miscellaneous_locked_screen

  # AJAX
  get 'ajax/email_compose', to: 'ajax#email_compose', as: :ajax_email_compose
  get 'ajax/email_list', to: 'ajax#email_list', as: :ajax_email_list
  get 'ajax/email_opened', to: 'ajax#email_opened', as: :ajax_email_opened
  get 'ajax/email_reply', to: 'ajax#email_reply', as: :ajax_email_reply
  get 'ajax/demo_widget', to: 'ajax#demo_widget', as: :ajax_demo_widget
  get 'ajax/data_list.json', to: 'ajax#data_list', as: :ajax_data_list
  get 'ajax/notify_mail', to: 'ajax#notify_mail', as: :ajax_notify_mail
  get 'ajax/notify_notifications',
      to: 'ajax#notify_notifications',
      as: :ajax_notify_notifications
  get 'ajax/notify_tasks', to: 'ajax#notify_tasks', as: :ajax_notify_tasks

  # Misc methods
  get '/home/set_locale', to: 'home#set_locale', as: :home_set_locale

  # CK editor
  mount Ckeditor::Engine => '/ckeditor'

end

RubyOnRails_seedProject/app/views/layouts/_footer.html.erb
<div class="page-footer">
  <div class="row">
    <div class="col-xs-12 col-sm-6">
      <span class="txt-color-white">Almacen <span class="hidden-xs"> - Evaluacion Rails</span> ©</span>
    </div>

  </div>
</div>

RubyOnRails_seedProject/app/views/layouts/_header.html.erb
<header id="header">
  <div id="logo-group">

    <!-- PLACE YOUR LOGO HERE -->

    <!-- END LOGO PLACEHOLDER -->

    <% if current_user && !@simulate_no_user %>
      <!-- Note: The activity badge color changes when clicked and resets the number to 0
      Suggestion: You may want to set a flag when this happens to tick off all checked messages / notifications -->


      <!-- AJAX-DROPDOWN : control this dropdown height, look and feel from the LESS variable file -->
      <div class="ajax-dropdown">

        <!-- the ID links are fetched via AJAX to the ajax container "ajax-notifications" -->
        <div class="btn-group btn-group-justified" data-toggle="buttons">

        </div>

        <!-- notification content -->

        <!-- end notification content -->

        <!-- footer: refresh area -->
            <span> Last updated on: 12/12/2013 9:43AM
              <button type="button" data-loading-text="<i class='fa fa-refresh fa-spin'></i> Loading..." class="btn btn-xs btn-default pull-right">
                <i class="fa fa-refresh"></i>
              </button>
            </span>
        <!-- end footer -->

      </div>
      <!-- END AJAX-DROPDOWN -->
    <% end %>
  </div>
  <%= yield :top_right %>

  <% if current_user && !@simulate_no_user %>

      <!-- logout button -->
      <div id="logout" class="btn-header transparent pull-right">
        <span>
          <%= link_to(destroy_user_session_path, title: 'Sign Out', data: {action: 'userLogout', 'logout-msg' => 'You can improve your security further after logging out by closing this opened browser'}) do %>
            <i class="fa fa-sign-out"></i>
          <% end %>
        </span>
      </div>
      <!-- end logout button -->

    </div>
    <!-- end pulled right: nav area -->
  <% end %>

</header>

RubyOnRails_seedProject/app/views/layouts/_left_panel.html.erb
<aside id="left-panel">

  <!-- User info -->
  <div class="login-info">

  </div>

  <nav>

    <ul>
      <%#= left_menu %>
      <%= link_to 'Shop',  shops_path , class: 'btn btn-info' %>
      <br><br><br><br><br>
      <%= link_to 'Pos',  pos_path , class: 'btn btn-success' %>
      <br><br><br><br><br>
      <%= link_to 'Sale',  sales_path , class: 'btn btn-danger' %>
      <br><br><br><br><br>
      <%= link_to 'Product',  products_path , class: 'btn btn-warning' %>
    </ul>
  </nav>

</aside>

RubyOnRails_seedProject/app/views/layouts/_locale_select.html.erb
<% @selected_locale = selected_locale %>
<ul class="header-dropdown-list hidden-xs">
  <li>
    <%= link_to '#', class: 'dropdown-toggle', data: {toggle: 'dropdown'} do %>
      <%= image_tag "blank.gif", class: "flag flag-#{@selected_locale[:flag]}", alt: @selected_locale[:alt_name] %> <span> <%= @selected_locale[:name] %> </span> <i class="fa fa-angle-down"></i>
  <% end %>
    <ul class="dropdown-menu pull-right">
      <% locale_list.each do |locale| %>
        <li class="<%= 'active' if locale[:locale] == @selected_locale[:locale] %>">
          <%= link_to home_set_locale_path(locale: locale[:locale]) do %>
            <%= image_tag "blank.gif", class: "flag flag-#{locale[:flag]}", alt: locale[:alt_name] %> <%= locale[:name] %>
          <% end %>
        </li>
      <% end %>
    </ul>
  </li>
</ul>

RubyOnRails_seedProject/app/views/layouts/_scripts.html.erb
<script type="text/javascript">
  $(document).ready(function() {
    pageSetUp();
  })
</script>

RubyOnRails_seedProject/app/views/layouts/_tiles.html.erb
<div id="shortcut">
  <ul>
    <li>
      <%= link_to root_path, class: 'jarvismetro-tile big-cubes bg-color-blue' do %>
        <span class="iconbox"> <i class="fa fa-envelope fa-4x"></i> <span>Mail <span class="label pull-right bg-color-darken">14</span></span> </span>
      <% end %>
    </li>
    <li>
      <%= link_to root_path, class: 'jarvismetro-tile big-cubes bg-color-orangeDark' do %>
        <span class="iconbox"> <i class="fa fa-calendar fa-4x"></i> <span>Calendar</span> </span>
      <% end %>
    </li>
    <li>
      <%= link_to root_path, class: 'jarvismetro-tile big-cubes bg-color-purple' do %>
        <span class="iconbox"> <i class="fa fa-map-marker fa-4x"></i> <span>Maps</span> </span>
      <% end %>
    </li>
    <li>
      <%= link_to root_path, class: 'jarvismetro-tile big-cubes bg-color-blueDark' do %>
        <span class="iconbox"> <i class="fa fa-book fa-4x"></i> <span>Invoice <span class="label pull-right bg-color-darken">99</span></span> </span>
      <% end %>
    </li>
    <li>
      <%= link_to root_path, class: 'jarvismetro-tile big-cubes bg-color-greenLight' do %>
        <span class="iconbox"> <i class="fa fa-picture-o fa-4x"></i> <span>Gallery </span> </span>
      <% end %>
    </li>
    <li>
      <%= link_to root_path, class: 'jarvismetro-tile big-cubes selected bg-color-pinkDark' do %>
        <span class="iconbox"> <i class="fa fa-user fa-4x"></i> <span>My Profile </span> </span>
      <% end %>
    </li>
  </ul>
</div>

RubyOnRails_seedProject/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en-us" id="<%= yield :html_id %>">
<head>
  <meta charset="utf-8">

  <title> SmartAdmin - Ruby on Rails </title>
  <%= csrf_meta_tags %>
  <meta name="description" content="">
  <meta name="author" content="">

  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">

  <%= stylesheet_link_tag 'application', media: 'screen' %>

  <!-- FAVICONS -->
  <%= favicon_link_tag 'favicon/favicon.ico' %>
  <%= favicon_link_tag 'favicon/favicon.ico', rel: 'icon' %>

  <!-- GOOGLE FONT -->
  <%= stylesheet_link_tag 'https://fonts.googleapis.com/css?family=Open+Sans:400italic,700italic,300,400,700' %>

  <!-- Specifying a Webpage Icon for Web Clip
     Ref: https://developer.apple.com/library/ios/documentation/AppleApplications/Reference/SafariWebContent/ConfiguringWebApplications/ConfiguringWebApplications.html -->
  <%= favicon_link_tag 'splash/sptouch-icon-iphone.png', type: 'image/png', rel: 'apple-touch-icon' %>
  <%= favicon_link_tag 'splash/touch-icon-ipad.png', type: 'image/png', sizes: '76x76', rel: 'apple-touch-icon' %>
  <%= favicon_link_tag 'splash/touch-icon-iphone-retina.png', type: 'image/png', sizes: '120x120', rel: 'apple-touch-icon' %>
  <%= favicon_link_tag 'splash/touch-icon-ipad-retina.png', type: 'image/png', sizes: '152x152', rel: 'apple-touch-icon' %>

  <!-- iOS web-app metas : hides Safari UI Components and Changes Status Bar Appearance -->
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">

  <!-- Startup image for web apps -->
  <%= favicon_link_tag 'splash/ipad-landscape.png', type: 'image/png', rel: 'apple-touch-startup-image', media: 'screen and (min-device-width: 481px) and (max-device-width: 1024px) and (orientation:landscape)' %>
  <%= favicon_link_tag 'splash/ipad-portrait.png', type: 'image/png', rel: 'apple-touch-startup-image', media: 'screen and (min-device-width: 481px) and (max-device-width: 1024px) and (orientation:portrait)' %>
  <%= favicon_link_tag 'splash/iphone.png', type: 'image/png', rel: 'apple-touch-startup-image', media: 'screen and (max-device-width: 320px)' %>

  <%= yield :head %>
</head>

<!--

TABLE OF CONTENTS.

Use search to find needed section.

===================================================================

|  01. #CSS Links                |  all CSS links and file paths  |
|  02. #FAVICONS                 |  Favicon links and file paths  |
|  03. #GOOGLE FONT              |  Google font link              |
|  04. #APP SCREEN / ICONS       |  app icons, screen backdrops   |
|  05. #BODY                     |  body tag                      |
|  06. #HEADER                   |  header tag                    |
|  07. #PROJECTS                 |  project lists                 |
|  08. #TOGGLE LAYOUT BUTTONS    |  layout buttons and actions    |
|  09. #MOBILE                   |  mobile view dropdown          |
|  10. #SEARCH                   |  search field                  |
|  11. #NAVIGATION               |  left panel & navigation       |
|  12. #RIGHT PANEL              |  right panel userlist          |
|  13. #MAIN PANEL               |  main panel                    |
|  14. #MAIN CONTENT             |  content holder                |
|  15. #PAGE FOOTER              |  page footer                   |
|  16. #SHORTCUT AREA            |  dropdown shortcuts area       |
|  17. #PLUGINS                  |  all scripts and plugins       |

===================================================================

-->

<!-- #BODY -->
<!-- Possible Classes

  * 'smart-style-{SKIN#}'
  * 'smart-rtl'         - Switch theme mode to RTL
  * 'menu-on-top'       - Switch to top navigation (no DOM change required)
  * 'no-menu'			  - Hides the menu completely
  * 'hidden-menu'       - Hides the main menu but still accessable by hovering over left edge
  * 'fixed-header'      - Fixes the header
  * 'fixed-navigation'  - Fixes the main menu
  * 'fixed-ribbon'      - Fixes breadcrumb
  * 'fixed-page-footer' - Fixes footer
  * 'container'         - boxed layout mode (non-responsive: will not work with fixed-navigation & fixed-ribbon)
-->
<body class="<%= yield :body_class %>">

<!-- HEADER -->
<%= render partial: 'layouts/header' unless @lock_screen %>
<!-- END HEADER -->

<!-- Left panel : Navigation area -->
<!-- Note: This width of the aside area can be adjusted through LESS variables -->
<%= render partial: 'layouts/left_panel' if current_user && !@simulate_no_user %>
<!-- END NAVIGATION -->

<!-- MAIN PANEL -->
<div id="main" role="main">
  <%= yield :ribbon %>
  <% if notice %>
    <div class="alert alert-success fade in">
      <button data-dismiss="alert" class="close">
        ×
      </button>
      <i class="fa-fw fa fa-check"></i>
      <%= notice %>
    </div>
  <% end %>
  <% if alert %>
    <div class="alert alert-warning fade in">
      <button data-dismiss="alert" class="close">
        ×
      </button>
      <i class="fa-fw fa fa-warning"></i>
      <%= alert %>
    </div>
  <% end %>
  <%= yield %>
</div>
<!-- END MAIN PANEL -->

<!-- PAGE FOOTER -->
<%= render partial: 'layouts/footer' if current_user && !@simulate_no_user %>
<!-- END PAGE FOOTER -->

<!-- SHORTCUT AREA : With large tiles (activated via clicking user name tag)
Note: These tiles are completely responsive,
you can add as many as you like
-->
<%= render partial: 'layouts/tiles' if current_user && !@simulate_no_user %>
<!-- END SHORTCUT AREA -->

<!--================================================== -->

<!-- PACE LOADER - turn this on if you want ajax loading to show (caution: uses lots of memory on iDevices)-->
<%= javascript_include_tag 'plugin/pace/pace', 'data-pace-options' => '{ "restartOnRequestAfter": true }' %>

<%= javascript_include_tag 'application' %>


<!--[if IE 8]>

<h1>Your browser is out of date, please update your browser by going to www.microsoft.com/download</h1>

<![endif]-->

<%= yield(:scripts).present? ? yield(:scripts) : render(partial: 'layouts/scripts') %>

<!-- Your GOOGLE ANALYTICS CODE Below -->
<script type="text/javascript">
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-XXXXXXXX-X']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script');
    ga.type = 'text/javascript';
    ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0];
    s.parentNode.insertBefore(ga, s);
  })();

</script>

</body>

</html>