RubyOnRails_seedProject/config/routes.rb
Rails.application.routes.draw do
  resources :pos
  resources :products
  resources :sales
  resources :shops
  get 'home/index'

  resources :profiles
  resources :name_profiles
  #resources :miscellaneous


  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #root :to => 'miscellaneous#blank_page'
  root :to => 'home#index'
  # Miscellaneous
  get 'miscellaneous/login',
      to: 'miscellaneous#login',
      as: :miscellaneous_login
  get 'miscellaneous/register',
      to: 'miscellaneous#register',
      as: :miscellaneous_register
  get 'miscellaneous/forgot_password',
      to: 'miscellaneous#forgot_password',
      as: :miscellaneous_forgot_password
  get 'miscellaneous/locked_screen',
      to: 'miscellaneous#locked_screen',
      as: :miscellaneous_locked_screen

  # AJAX
  get 'ajax/email_compose', to: 'ajax#email_compose', as: :ajax_email_compose
  get 'ajax/email_list', to: 'ajax#email_list', as: :ajax_email_list
  get 'ajax/email_opened', to: 'ajax#email_opened', as: :ajax_email_opened
  get 'ajax/email_reply', to: 'ajax#email_reply', as: :ajax_email_reply
  get 'ajax/demo_widget', to: 'ajax#demo_widget', as: :ajax_demo_widget
  get 'ajax/data_list.json', to: 'ajax#data_list', as: :ajax_data_list
  get 'ajax/notify_mail', to: 'ajax#notify_mail', as: :ajax_notify_mail
  get 'ajax/notify_notifications',
      to: 'ajax#notify_notifications',
      as: :ajax_notify_notifications
  get 'ajax/notify_tasks', to: 'ajax#notify_tasks', as: :ajax_notify_tasks

  # Misc methods
  get '/home/set_locale', to: 'home#set_locale', as: :home_set_locale

  # CK editor
  mount Ckeditor::Engine => '/ckeditor'

end

RubyOnRails_seedProject/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

RubyOnRails_seedProject/app/helpers/home_helper.rb
module HomeHelper
end

RubyOnRails_seedProject/app/views/home/index.html.erb
<h1>Home#index</h1>



<p id="notice"><%= notice %></p>


<div class="row wrapper border-bottom white-bg page-heading">
  <div class="col-lg-10">
    <ol class="breadcrumb">

    </ol>
  </div>
  <div class="col-lg-2">
  </div>
</div>

<div class="wrapper wrapper-content animated fadeInRight">
  <div class="row">
    <div class="ibox float-e-margins">
    </div>
    <div class="inbox-content">
      <table class="table table-hover table-striped table-responsive">
      </table>

      <div class="col-md-12 hr-line-dashed"></div>
      <p id="notice"><%= notice %></p>
      <%#= link_to 'New profile', new_profile_path, class: 'btn btn-w-m btn-success' %>
    </div>
  </div>
</div>