RubyOnRails_Full_version/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'dashboard#analytics'
  get 'dashboards/dashboard-social',
      to: 'dashboard#social',
      as: :dashboard_social

  # Smartadmin intel
  get 'smartadmin_intel/app_layouts',
      to: 'smartadmin_intel#app_layouts',
      as: :smartadmin_intel_app_layouts
  get 'smartadmin_intel/app_settings',
      to: 'smartadmin_intel#app_settings',
      as: :smartadmin_intel_app_settings
  get 'smartadmin_intel/prebuilt_skins',
      to: 'smartadmin_intel#prebuilt_skins',
      as: :smartadmin_intel_prebuilt_skins
  get 'outlook/inbox', to: 'outlook#inbox', as: :outlook_inbox

  # AJAX
  get 'ajax/email_compose', to: 'ajax#email_compose', as: :ajax_email_compose
  get 'ajax/email_list', to: 'ajax#email_list', as: :ajax_email_list
  get 'ajax/email_opened', to: 'ajax#email_opened', as: :ajax_email_opened
  get 'ajax/email_reply', to: 'ajax#email_reply', as: :ajax_email_reply
  get 'ajax/demo_widget', to: 'ajax#demo_widget', as: :ajax_demo_widget
  get 'ajax/data_list.json', to: 'ajax#data_list', as: :ajax_data_list
  get 'ajax/notify_mail', to: 'ajax#notify_mail', as: :ajax_notify_mail
  get 'ajax/notify_notifications',
      to: 'ajax#notify_notifications',
      as: :ajax_notify_notifications
  get 'ajax/notify_tasks', to: 'ajax#notify_tasks', as: :ajax_notify_tasks

  # Graphs
  get 'graphs/flot_chart', to: 'graphs#flot_chart', as: :graphs_flot_chart
  get 'graphs/morris_charts',
      to: 'graphs#morris_charts',
      as: :graphs_morris_charts
  get 'graphs/sparklines', to: 'graphs#sparklines', as: :graphs_sparklines
  get 'graphs/easy_pie_charts',
      to: 'graphs#easy_pie_charts',
      as: :graphs_easy_pie_charts
  get 'graphs/dygraphs', to: 'graphs#dygraphs', as: :graphs_dygraphs
  get 'graphs/chart_js', to: 'graphs#chart_js', as: :graphs_chart_js
  get 'graphs/highchart_table',
      to: 'graphs#highchart_table',
      as: :graphs_highchart_table

  # Tables
  get 'tables/normal_tables',
      to: 'tables#normal_tables',
      as: :tables_normal_tables
  get 'tables/data_tables', to: 'tables#data_tables', as: :tables_data_tables
  get 'tables/jquery_grid', to: 'tables#jquery_grid', as: :tables_jquery_grid

  # Forms
  get 'forms/smart_form_elements',
      to: 'forms#smart_form_elements',
      as: :forms_smart_form_elements
  get 'forms/smart_form_layouts',
      to: 'forms#smart_form_layouts',
      as: :forms_smart_form_layouts
  get 'forms/smart_form_validations',
      to: 'forms#smart_form_validations',
      as: :forms_smart_form_validations
  get 'forms/bootstrap_form_elements',
      to: 'forms#bootstrap_form_elements',
      as: :forms_bootstrap_form_elements
  get 'forms/bootstrap_form_validation',
      to: 'forms#bootstrap_form_validation',
      as: :forms_bootstrap_form_validation
  get 'forms/form_plugins', to: 'forms#form_plugins', as: :forms_form_plugins
  get 'forms/wizards', to: 'forms#wizards', as: :forms_wizards
  get 'forms/bootstrap_editors',
      to: 'forms#bootstrap_editors',
      as: :forms_bootstrap_editors
  get 'forms/dropzone', to: 'forms#dropzone', as: :forms_dropzone
  get 'forms/image_cropping',
      to: 'forms#image_cropping',
      as: :forms_image_cropping
  get 'forms/ck_editor', to: 'forms#ck_editor', as: :forms_ck_editor

  # UI Elements
  get 'ui_elements/general_elements',
      to: 'ui_elements#general_elements',
      as: :ui_elements_general_elements
  get 'ui_elements/buttons', to: 'ui_elements#buttons', as: :ui_elements_buttons
  get 'ui_elements/icons/font_awesome',
      to: 'ui_elements#icons_font_awesome',
      as: :ui_elements_icons_font_awesome
  get 'ui_elements/icons/glyph_icons',
      to: 'ui_elements#icons_glyph_icons',
      as: :ui_elements_icons_glyph_icons
  get 'ui_elements/icons/flags',
      to: 'ui_elements#icons_flags',
      as: :ui_elements_icons_flags
  get 'ui_elements/grid', to: 'ui_elements#grid', as: :ui_elements_grid
  get 'ui_elements/tree_view',
      to: 'ui_elements#tree_view',
      as: :ui_elements_tree_view
  get 'ui_elements/nestable_lists',
      to: 'ui_elements#nestable_lists',
      as: :ui_elements_nestable_lists
  get 'ui_elements/jquery_ui',
      to: 'ui_elements#jquery_ui',
      as: :ui_elements_jquery_ui
  get 'ui_elements/typography',
      to: 'ui_elements#typography',
      as: :ui_elements_typography

  # Widgets
  get 'widgets/', to: 'widgets#index', as: :widgets

  # Cool Features
  get 'cool_features/calendar',
      to: 'cool_features#calendar',
      as: :cool_features_calendar
  get 'cool_features/gmap_skins',
      to: 'cool_features#gmap_skins',
      as: :cool_features_gmap_skins

  # App Views
  get 'app_views/projects', to: 'app_views#projects', as: :app_views_projects
  get 'app_views/blog', to: 'app_views#blog', as: :app_views_blog
  get 'app_views/gallery', to: 'app_views#gallery', as: :app_views_gallery
  get 'app_views/forum_layout_general_view',
      to: 'app_views#forum_layout_general_view',
      as: :app_views_forum_layout_general_view
  get 'app_views/forum_layout_topic_view',
      to: 'app_views#forum_layout_topic_view',
      as: :app_views_forum_layout_topic_view
  get 'app_views/forum_layout_post_view',
      to: 'app_views#forum_layout_post_view',
      as: :app_views_forum_layout_post_view
  get 'app_views/profile', to: 'app_views#profile', as: :app_views_profile
  get 'app_views/timeline', to: 'app_views#timeline', as: :app_views_timeline
  get 'app_views/search_page',
      to: 'app_views#search_page',
      as: :app_views_search_page

  # E-Commerce
  get 'e_commerce/orders', to: 'e_commerce#orders', as: :e_commerce_orders
  get 'e_commerce/products_view',
      to: 'e_commerce#products_view',
      as: :e_commerce_products_view
  get 'e_commerce/products_detail',
      to: 'e_commerce#products_detail',
      as: :e_commerce_products_detail

  # Miscellaneous
  get 'miscellaneous/pricing_tables',
      to: 'miscellaneous#pricing_tables',
      as: :miscellaneous_pricing_tables
  get 'miscellaneous/invoice',
      to: 'miscellaneous#invoice',
      as: :miscellaneous_invoice
  get 'miscellaneous/login',
      to: 'miscellaneous#login',
      as: :miscellaneous_login
  get 'miscellaneous/register',
      to: 'miscellaneous#register',
      as: :miscellaneous_register
  get 'miscellaneous/forgot_password',
      to: 'miscellaneous#forgot_password',
      as: :miscellaneous_forgot_password
  get 'miscellaneous/locked_screen',
      to: 'miscellaneous#locked_screen',
      as: :miscellaneous_locked_screen
  get 'miscellaneous/error_404',
      to: 'miscellaneous#error_404',
      as: :miscellaneous_error_404
  get 'miscellaneous/error_500',
      to: 'miscellaneous#error_500',
      as: :miscellaneous_error_500
  get 'miscellaneous/blank_page',
      to: 'miscellaneous#blank_page',
      as: :miscellaneous_blank_page

  # Smart chat API
  get 'smart_chat_api/',
      to: 'smart_chat_api#index',
      as: :smart_chat_api

  # Misc methods
  get '/home/set_locale', to: 'home#set_locale', as: :home_set_locale

  # CK editor
  mount Ckeditor::Engine => '/ckeditor'
end

RubyOnRails_Full_version/app/controllers/app_views_controller.rb
# App Views section
class AppViewsController < ApplicationController
  def projects
  end

  def blog
  end

  def gallery
  end

  def forum_layout_general_view
  end

  def forum_layout_topic_view
  end

  def forum_layout_post_view
  end

  def profile
  end

  def timeline
  end

  def search_page
  end
end

RubyOnRails_Full_version/app/views/app_views/forum_layout_post_view.html.erb
<% content_for :ribbon do %>
<!-- RIBBON -->
<div id="ribbon">

  <span class="ribbon-button-alignment">
    <span id="refresh" class="btn btn-ribbon" data-action="resetWidgets" data-title="refresh"  rel="tooltip" data-placement="bottom" data-original-title="<i class='text-warning fa fa-warning'></i> Warning! This will reset all your widget settings." data-html="true">
      <i class="fa fa-refresh"></i>
    </span>
  </span>

  <!-- breadcrumb -->
  <ol class="breadcrumb">
    <li>Home</li><li>App Views</li><li>Forum Layout</li><li>Post View</li>
  </ol>
  <!-- end breadcrumb -->

  <!-- You can also add more buttons to the
  ribbon for further usability

  Example below:

  <span class="ribbon-button-alignment pull-right">
  <span id="search" class="btn btn-ribbon hidden-xs" data-title="search"><i class="fa-grid"></i> Change Grid</span>
  <span id="add" class="btn btn-ribbon hidden-xs" data-title="add"><i class="fa-plus"></i> Add</span>
  <span id="search" class="btn btn-ribbon" data-title="search"><i class="fa-search"></i> <span class="hidden-mobile">Search</span></span>
  </span> -->

</div>
<!-- END RIBBON -->
<% end %>

<!-- MAIN CONTENT -->
<div id="content">

  <!-- Bread crumb is created dynamically -->
  <!-- row -->
  <div class="row">

    <!-- col -->
    <div class="col-xs-12 col-sm-3 col-md-4 col-lg-4">
      <h1 class="page-title txt-color-blueDark"><!-- PAGE HEADER --><i class="fa-fw fa fa-puzzle-piece"></i> App Views <span>>
        Forum Layout > Post View </span></h1>
    </div>
    <!-- end col -->

    <!-- right side of the page with the sparkline graphs -->
    <!-- col -->
    <div class="col-xs-12 col-sm-9 col-md-8 col-lg-8">
      <!-- sparks -->
      <ul id="sparks">
        <li class="sparks-info">
          <h5> My Income <span class="txt-color-blue">$47,171</span></h5>
          <div class="sparkline txt-color-blue hidden-mobile">
            1300, 1877, 2500, 2577, 2000, 2100, 3000, 2700, 3631, 2471, 2700, 3631, 2471
          </div>
        </li>
        <li class="sparks-info">
          <h5> Site Traffic <span class="txt-color-purple"><i class="fa fa-arrow-circle-up" title="Increased"></i>&nbsp;45%</span></h5>
          <div class="sparkline txt-color-purple hidden-mobile">
            110,150,300,130,400,240,220,310,220,300, 270, 210
          </div>
        </li>
        <li class="sparks-info">
          <h5> Site Orders <span class="txt-color-greenDark"><i class="fa fa-shopping-cart"></i>&nbsp;2447</span></h5>
          <div class="sparkline txt-color-greenDark hidden-mobile">
            110,150,300,130,400,240,220,310,220,300, 270, 210
          </div>
        </li>
      </ul>
      <!-- end sparks -->
    </div>
    <!-- end col -->

  </div>
  <!-- end row -->

  <!-- row -->
  <div class="row">

    <div class="col-sm-12">

      <div class="well">

        <table class="table table-striped table-forum">
          <thead>
            <tr>
              <th colspan="2"><%= link_to ' Projects ', app_views_forum_layout_general_view_path %> > <%= link_to 'Business Requirement Docs ', app_views_forum_layout_topic_view_path %> > Nam quam nunc blandit vel </th>
            </tr>
          </thead>
          <tbody>
            <!-- Post -->
            <tr>
              <td class="text-center">
                <%= link_to app_views_profile_path do %>
                  <%= image_tag 'flags/us.png', alt: '' %> &nbsp; <strong>John Doe</strong>
                <% end %>
              </td>
              <td>on <em>Jan 1, 2014 - 12:00am</em></td>
            </tr>
            <tr>
              <td class="text-center" style="width: 12%;">
              <div class="push-bit">
                <%= link_to app_views_profile_path do %>
                  <%= image_tag 'avatars/sunny.png', width: '50', alt: 'avatar', class: 'online' %>
                <% end %>
              </div><small>473 Posts</small></td>
              <td>
              <p>

                Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet.
              </p><h5>Forecast Pie</h5><span class="sparkline display-inline margin-bottom-10" data-sparkline-type="pie" data-sparkline-offset="90" data-sparkline-piesize="150px"> 33,20,10 </span>
              <p>
                Fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viv.
              </p><em>- John Doe
              <br>
              CEO, SmartAdmin</em></td>
            </tr>
            <!-- end Post -->

            <!-- Post -->
            <tr>
              <td class="text-center">
                <%= link_to app_views_profile_path do %>
                  <%= image_tag 'flags/es.png', alt: '' %> &nbsp; <strong>Sadi Orlaf</strong>
                <% end %>
              </td>
              <td>on <em>Jan 1, 2014 - 12:00am</em></td>
            </tr>
            <tr>
              <td class="text-center" style="width: 12%;">
              <div class="push-bit">
                <%= link_to app_views_profile_path do %>
                  <%= image_tag 'avatars/5.png', width: '50', alt: 'avatar', class: 'offline' %>
                <% end %>
              </div><small>473 Posts</small></td>
              <td>
              <p>

                Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet.
              </p><em>- Sadi Orlaf
              <br>
              Executive, SmartAdmin</em>
              <div class="forum-attachment">
                2 attachment(s) — <a href="javascript:void(0);"> Download all attachments</a>
                <ul class="list-inline margin-top-10">
                  <li class="well well-sm padding-5">
                    <strong>rocketlaunch.jpg</strong>
                    <br>
                    400 kb
                    <br>
                    <a href="javascript:void(0);"> Download</a> | <a href="javascript:void(0);"> View</a>
                  </li>
                  <li class="well well-sm padding-5">
                    <strong>budget.xsl</strong>
                    <br>
                    400 kb
                    <br>
                    <a href="javascript:void(0);"> Download</a> | <a href="javascript:void(0);"> Share</a>
                  </li>
                </ul>
              </div></td>
            </tr>
            <!-- end Post -->

            <!-- Post -->
            <tr>
              <td class="text-center">
                <%= link_to app_views_profile_path do %>
                  <%= image_tag 'flags/us.png', alt: '' %> &nbsp; <strong>Me</strong>
                <% end %>
              </td>
              <td><em>Today</em></td>
            </tr>
            <tr>
              <td class="text-center" style="width: 12%;">
              <div class="push-bit">
                <%= link_to app_views_profile_path do %>
                  <%= image_tag 'avatars/sunny.png', width: '50', alt: 'avatar', class: 'online' %>
                <% end %>
              </div><small>473 Posts</small></td>
              <td><div id="forumPost"></div>

              <button class="btn btn-primary margin-top-10">
                Post
              </button>
              <button class="btn btn-success margin-top-10">
                Save for later
              </button></td>
            </tr>
            <!-- end Post -->

          </tbody>
        </table>

        <div class="text-center">
          <ul class="pagination pagination-sm">
            <li class="disabled">
              <a href="javascript:void(0);">Prev</a>
            </li>
            <li class="active">
              <a href="javascript:void(0);">1</a>
            </li>
            <li>
              <a href="javascript:void(0);">2</a>
            </li>
            <li>
              <a href="javascript:void(0);">3</a>
            </li>
            <li>
              <a href="javascript:void(0);">...</a>
            </li>
            <li>
              <a href="javascript:void(0);">99</a>
            </li>
            <li>
              <a href="javascript:void(0);">Next</a>
            </li>
          </ul>
        </div>

      </div>
    </div>

  </div>

  <!-- end row -->

</div>
<!-- END MAIN CONTENT -->

<% content_for :scripts do %>
  <script type="text/javascript">
    // DO NOT REMOVE : GLOBAL FUNCTIONS!

    $(document).ready(function() {

      pageSetUp();

      $('#forumPost').summernote({
        height : 180,
        focus : false,
        tabsize : 2
      });

    })

  </script>
<% end %>

RubyOnRails_Full_version/app/views/app_views/projects.html.erb
<% content_for :ribbon do %>
<!-- RIBBON -->
<div id="ribbon">

  <span class="ribbon-button-alignment">
    <span id="refresh" class="btn btn-ribbon" data-action="resetWidgets" data-title="refresh"  rel="tooltip" data-placement="bottom" data-original-title="<i class='text-warning fa fa-warning'></i> Warning! This will reset all your widget settings." data-html="true">
      <i class="fa fa-refresh"></i>
    </span>
  </span>

  <!-- breadcrumb -->
  <ol class="breadcrumb">
    <li>Home</li><li>App Views</li><li>Projects</li>
  </ol>
  <!-- end breadcrumb -->

  <!-- You can also add more buttons to the
  ribbon for further usability

  Example below:

  <span class="ribbon-button-alignment pull-right">
  <span id="search" class="btn btn-ribbon hidden-xs" data-title="search"><i class="fa-grid"></i> Change Grid</span>
  <span id="add" class="btn btn-ribbon hidden-xs" data-title="add"><i class="fa-plus"></i> Add</span>
  <span id="search" class="btn btn-ribbon" data-title="search"><i class="fa-search"></i> <span class="hidden-mobile">Search</span></span>
  </span> -->

</div>
<!-- END RIBBON -->
<% end %>



<!-- MAIN CONTENT -->
<div id="content">

  <!-- row -->
  <div class="row">

    <!-- col -->
    <div class="col-xs-12 col-sm-7 col-md-7 col-lg-4">
      <h1 class="page-title txt-color-blueDark">

        <!-- PAGE HEADER -->
        <i class="fa-fw fa fa-puzzle-piece"></i>
          App Views
        <span>>
          Project
        </span>
      </h1>
    </div>
    <!-- end col -->

    <!-- right side of the page with the sparkline graphs -->
    <!-- col -->
    <div class="col-xs-12 col-sm-5 col-md-5 col-lg-8">
      <!-- sparks -->
      <ul id="sparks">
        <li class="sparks-info">
          <h5> My Income <span class="txt-color-blue">$47,171</span></h5>
          <div class="sparkline txt-color-blue hidden-mobile hidden-md hidden-sm">
            1300, 1877, 2500, 2577, 2000, 2100, 3000, 2700, 3631, 2471, 2700, 3631, 2471
          </div>
        </li>
        <li class="sparks-info">
          <h5> Site Traffic <span class="txt-color-purple"><i class="fa fa-arrow-circle-up" data-rel="bootstrap-tooltip" title="Increased"></i>&nbsp;45%</span></h5>
          <div class="sparkline txt-color-purple hidden-mobile hidden-md hidden-sm">
            110,150,300,130,400,240,220,310,220,300, 270, 210
          </div>
        </li>
        <li class="sparks-info">
          <h5> Site Orders <span class="txt-color-greenDark"><i class="fa fa-shopping-cart"></i>&nbsp;2447</span></h5>
          <div class="sparkline txt-color-greenDark hidden-mobile hidden-md hidden-sm">
            110,150,300,130,400,240,220,310,220,300, 270, 210
          </div>
        </li>
      </ul>
      <!-- end sparks -->
    </div>
    <!-- end col -->

  </div>
  <!-- end row -->

  <!--
    The ID "widget-grid" will start to initialize all widgets below
    You do not need to use widgets if you dont want to. Simply remove
    the <section></section> and you can use wells or panels instead
    -->

  <!-- widget grid -->
  <section id="widget-grid" class="">

    <!-- row -->
    <div class="row">

      <!-- NEW WIDGET START -->
      <article class="col-xs-12 col-sm-12 col-md-12 col-lg-12">

        <div class="alert alert-info">
          <strong>NOTE:</strong> All the data is loaded from a seperate JSON file
        </div>

        <!-- Widget ID (each widget will need unique ID)-->
        <div class="jarviswidget well" id="wid-id-0">
          <!-- widget options:
            usage: <div class="jarviswidget" id="wid-id-0" data-widget-editbutton="false">

            data-widget-colorbutton="false"
            data-widget-editbutton="false"
            data-widget-togglebutton="false"
            data-widget-deletebutton="false"
            data-widget-fullscreenbutton="false"
            data-widget-custombutton="false"
            data-widget-collapsed="true"
            data-widget-sortable="false"

          -->
          <header>
            <span class="widget-icon"> <i class="fa fa-comments"></i> </span>
            <h2>Widget Title </h2>

          </header>

          <!-- widget div-->
          <div>

            <!-- widget edit box -->
            <div class="jarviswidget-editbox">
              <!-- This area used as dropdown edit box -->
              <input class="form-control" type="text">
            </div>
            <!-- end widget edit box -->

            <!-- widget content -->
            <div class="widget-body no-padding">

              <table id="example" class="display projects-table table table-striped table-bordered table-hover" cellspacing="0" width="100%">
                    <thead>
                        <tr>
                            <th></th><th>Projects</th><th><i class="fa fa-fw fa-user text-muted hidden-md hidden-sm hidden-xs"></i> EST</th>
                            <th>Contacts</th>
                            <th>Status</th>
                            <th><i class="fa fa-circle txt-color-darken font-xs"></i> Target/ <i class="fa fa-circle text-danger font-xs"></i> Actual</th>
                            <th><i class="fa fa-fw fa-calendar text-muted hidden-md hidden-sm hidden-xs"></i> Starts</th>
                            <th><i class="fa fa-fw fa-calendar text-muted hidden-md hidden-sm hidden-xs"></i> Ends</th>
                            <th>Tracker</th>
                        </tr>
                    </thead>
                </table>

            </div>
            <!-- end widget content -->

          </div>
          <!-- end widget div -->

        </div>
        <!-- end widget -->

      </article>
      <!-- WIDGET END -->

    </div>

    <!-- end row -->

    <!-- row -->

    <div class="row">

      <!-- a blank row to get started -->
      <div class="col-sm-12">
        <!-- your contents here -->
      </div>

    </div>

    <!-- end row -->

  </section>
  <!-- end widget grid -->

</div>
<!-- END MAIN CONTENT -->

<% content_for :scripts do %>
  <script type="text/javascript">

    $(document).ready(function() {

      /* DO NOT REMOVE : GLOBAL FUNCTIONS!
       *
       * pageSetUp(); WILL CALL THE FOLLOWING FUNCTIONS
       *
       * // activate tooltips
       * $("[rel=tooltip]").tooltip();
       *
       * // activate popovers
       * $("[rel=popover]").popover();
       *
       * // activate popovers with hover states
       * $("[rel=popover-hover]").popover({ trigger: "hover" });
       *
       * // activate inline charts
       * runAllCharts();
       *
       * // setup widgets
       * setup_widgets_desktop();
       *
       * // run form elements
       * runAllForms();
       *
       ********************************
       *
       * pageSetUp() is needed whenever you load a page.
       * It initializes and checks for all basic elements of the page
       * and makes rendering easier.
       *
       */

      pageSetUp();

      /*
       * ALL PAGE RELATED SCRIPTS CAN GO BELOW HERE
       * eg alert("my home function");
       *
       * var pagefunction = function() {
       *   ...
       * }
       * loadScript("js/plugin/_PLUGIN_NAME_.js", pagefunction);
       *
       * TO LOAD A SCRIPT:
       * var pagefunction = function (){
       *  loadScript(".../plugin.js", run_after_loaded);
       * }
       *
       * OR
       *
       * loadScript(".../plugin.js", run_after_loaded);
       */

      /* Formatting function for row details - modify as you need */
      function format ( d ) {
        // `d` is the original data object for the row
        return '<table cellpadding="5" cellspacing="0" border="0" class="table table-hover table-condensed">'+
          '<tr>'+
          '<td style="width:100px">Project Title:</td>'+
          '<td>'+d.name+'</td>'+
          '</tr>'+
          '<tr>'+
          '<td>Deadline:</td>'+
          '<td>'+d.ends+'</td>'+
          '</tr>'+
          '<tr>'+
          '<td>Extra info:</td>'+
          '<td>And any further details here (images etc)...</td>'+
          '</tr>'+
          '<tr>'+
          '<td>Comments:</td>'+
          '<td>'+d.comments+'</td>'+
          '</tr>'+
          '<tr>'+
          '<td>Action:</td>'+
          '<td>'+d.action+'</td>'+
          '</tr>'+
          '</table>';
      }

      // clears the variable if left blank
      var table = $('#example').DataTable( {
        "sDom": "<'dt-toolbar'<'col-xs-12 col-sm-6'f><'col-sm-6 col-xs-12 hidden-xs'l>r>"+
        "t"+
        "<'dt-toolbar-footer'<'col-sm-6 col-xs-12 hidden-xs'i><'col-xs-12 col-sm-6'p>>",
        "ajax": "<%= ajax_data_list_path %>",
        "bDestroy": true,
        "iDisplayLength": 15,
        "oLanguage": {
          "sSearch": '<span class="input-group-addon"><i class="glyphicon glyphicon-search"></i></span>'
        },
        "columns": [
          {
            "class":          'details-control',
            "orderable":      false,
            "data":           null,
            "defaultContent": ''
          },
          { "data": "name" },
          { "data": "est" },
          { "data": "contacts" },
          { "data": "status" },
          { "data": "target-actual" },
          { "data": "starts" },
          { "data": "ends" },
          { "data": "tracker" },
        ],
        "order": [[1, 'asc']],
        "fnDrawCallback": function( oSettings ) {
          runAllCharts()
        }
      } );



      // Add event listener for opening and closing details
      $('#example tbody').on('click', 'td.details-control', function () {
        var tr = $(this).closest('tr');
        var row = table.row( tr );

        if ( row.child.isShown() ) {
          // This row is already open - close it
          row.child.hide();
          tr.removeClass('shown');
        }
        else {
          // Open this row
          row.child( format(row.data()) ).show();
          tr.addClass('shown');
        }
      });

    })

  </script>
<% end %>